"""users + actor/updated_by columns

Revision ID: 22b15af22754
Revises: 23a5b370074d
Create Date: 2026-08-23 14:23:11.363914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b15af22754'
down_revision: Union[str, Sequence[str], None] = '23a5b370074d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('can_view_price', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('project_events', sa.Column('actor', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('rule_settings', sa.Column('updated_by', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('scoring_templates', sa.Column('updated_by', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('settings', sa.Column('updated_by', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('tasks', sa.Column('actor', sa.String(length=64), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'actor')
    op.drop_column('settings', 'updated_by')
    op.drop_column('scoring_templates', 'updated_by')
    op.drop_column('rule_settings', 'updated_by')
    op.drop_column('project_events', 'actor')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
