"""config center: scoring_templates/rule_settings/settings/llm_usage

Revision ID: 23a5b370074d
Revises: dd556c5b7f50
Create Date: 2026-08-23 14:02:17.084745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a5b370074d'
down_revision: Union[str, Sequence[str], None] = 'dd556c5b7f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_created_at'), 'llm_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_purpose'), 'llm_usage', ['purpose'], unique=False)
    op.create_table('rule_settings',
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('level_override', sa.String(length=8), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('scoring_templates',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_templates_kind'), 'scoring_templates', ['kind'], unique=False)
    op.create_index(op.f('ix_scoring_templates_name'), 'scoring_templates', ['name'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_index(op.f('ix_scoring_templates_name'), table_name='scoring_templates')
    op.drop_index(op.f('ix_scoring_templates_kind'), table_name='scoring_templates')
    op.drop_table('scoring_templates')
    op.drop_table('rule_settings')
    op.drop_index(op.f('ix_llm_usage_purpose'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_created_at'), table_name='llm_usage')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
