"""kb tables: certificates/personnel/performances/financials/products/test_reports/boilerplates/attachments

Revision ID: 47d040276d15
Revises: 9d5b301eb596
Create Date: 2026-08-22 23:21:24.551387

"""
from typing import Sequence, Union

import datetime as dt
import json
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d040276d15'
down_revision: Union[str, Sequence[str], None] = '9d5b301eb596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_attachments',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['profiles.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_attachments_company'), 'kb_attachments', ['company'], unique=False)
    op.create_index(op.f('ix_kb_attachments_sha256'), 'kb_attachments', ['sha256'], unique=False)
    op.create_table('kb_boilerplates',
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['profiles.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_boilerplates_company'), 'kb_boilerplates', ['company'], unique=False)
    op.create_index(op.f('ix_kb_boilerplates_topic'), 'kb_boilerplates', ['topic'], unique=False)
    op.create_table('kb_certificates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=False),
    sa.Column('cert_type', sa.String(length=64), nullable=False),
    sa.Column('valid_until', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['profiles.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_certificates_company'), 'kb_certificates', ['company'], unique=False)
    op.create_index(op.f('ix_kb_certificates_valid_until'), 'kb_certificates', ['valid_until'], unique=False)
    op.create_table('kb_financials',
    sa.Column('year', sa.String(length=8), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['profiles.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_financials_company'), 'kb_financials', ['company'], unique=False)
    op.create_index(op.f('ix_kb_financials_year'), 'kb_financials', ['year'], unique=False)
    op.create_table('kb_performances',
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('buyer', sa.String(length=255), nullable=False),
    sa.Column('buyer_is_end_user', sa.Boolean(), nullable=True),
    sa.Column('amount_wan', sa.Float(), nullable=True),
    sa.Column('signed_date', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['profiles.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_performances_company'), 'kb_performances', ['company'], unique=False)
    op.create_index(op.f('ix_kb_performances_signed_date'), 'kb_performances', ['signed_date'], unique=False)
    op.create_table('kb_personnel',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['profiles.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_personnel_company'), 'kb_personnel', ['company'], unique=False)
    op.create_table('kb_products',
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['profiles.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_products_company'), 'kb_products', ['company'], unique=False)
    op.create_index(op.f('ix_kb_products_model'), 'kb_products', ['model'], unique=False)
    op.create_table('kb_test_reports',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('valid_until', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['profiles.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_test_reports_company'), 'kb_test_reports', ['company'], unique=False)
    op.create_index(op.f('ix_kb_test_reports_valid_until'), 'kb_test_reports', ['valid_until'], unique=False)
    # ### end Alembic commands ###
    _split_legacy_profiles()


# 旧库 profiles.data 内整体 JSON 的列表 → 子表；迁移脚本须冻结，故不 import jb_kb（字段映射在此内联）。
_LEGACY = {
    "certificates": ("kb_certificates", ("name", "number", "cert_type", "valid_until")),
    "personnel": ("kb_personnel", ("name", "title")),
    "performances": ("kb_performances", ("project", "buyer", "buyer_is_end_user", "amount_wan", "signed_date")),
    "financials": ("kb_financials", ("year",)),
    "products": ("kb_products", ("model", "name", "category")),
    "test_reports": ("kb_test_reports", ("name", "report_type", "valid_until")),
    "boilerplates": ("kb_boilerplates", ("topic", "title", "approved")),
}
_NULLABLE = {"buyer_is_end_user", "amount_wan"}


def _split_legacy_profiles() -> None:
    bind = op.get_bind()
    meta = sa.MetaData()
    profiles = sa.Table("profiles", meta, autoload_with=bind)
    tables = {k: sa.Table(t, meta, autoload_with=bind) for k, (t, _) in _LEGACY.items()}
    now = dt.datetime.utcnow()
    for name, data in bind.execute(sa.select(profiles.c.name, profiles.c.data)).all():
        if isinstance(data, str):
            data = json.loads(data)
        data = dict(data or {})
        changed = False
        for key, (_, cols) in _LEGACY.items():
            items = data.pop(key, None)
            if items is None:
                continue
            changed = True
            for item in items:
                item = dict(item)
                rid = item.get("id") or uuid.uuid4().hex[:12]
                item["id"] = rid
                vals = {c: item.get(c) for c in cols}
                for c, v in vals.items():
                    if v is None and c not in _NULLABLE:
                        vals[c] = False if c == "approved" else ""
                if key == "boilerplates":
                    status = "approved" if item.get("approved") else "draft"
                else:
                    status = item.get("status") or "approved"
                bind.execute(tables[key].insert().values(
                    id=rid, company=name, status=status, data=item,
                    created_at=now, updated_at=now, **vals))
        if changed:
            bind.execute(profiles.update().where(profiles.c.name == name).values(data=data))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_test_reports_valid_until'), table_name='kb_test_reports')
    op.drop_index(op.f('ix_kb_test_reports_company'), table_name='kb_test_reports')
    op.drop_table('kb_test_reports')
    op.drop_index(op.f('ix_kb_products_model'), table_name='kb_products')
    op.drop_index(op.f('ix_kb_products_company'), table_name='kb_products')
    op.drop_table('kb_products')
    op.drop_index(op.f('ix_kb_personnel_company'), table_name='kb_personnel')
    op.drop_table('kb_personnel')
    op.drop_index(op.f('ix_kb_performances_signed_date'), table_name='kb_performances')
    op.drop_index(op.f('ix_kb_performances_company'), table_name='kb_performances')
    op.drop_table('kb_performances')
    op.drop_index(op.f('ix_kb_financials_year'), table_name='kb_financials')
    op.drop_index(op.f('ix_kb_financials_company'), table_name='kb_financials')
    op.drop_table('kb_financials')
    op.drop_index(op.f('ix_kb_certificates_valid_until'), table_name='kb_certificates')
    op.drop_index(op.f('ix_kb_certificates_company'), table_name='kb_certificates')
    op.drop_table('kb_certificates')
    op.drop_index(op.f('ix_kb_boilerplates_topic'), table_name='kb_boilerplates')
    op.drop_index(op.f('ix_kb_boilerplates_company'), table_name='kb_boilerplates')
    op.drop_table('kb_boilerplates')
    op.drop_index(op.f('ix_kb_attachments_sha256'), table_name='kb_attachments')
    op.drop_index(op.f('ix_kb_attachments_company'), table_name='kb_attachments')
    op.drop_table('kb_attachments')
    # ### end Alembic commands ###
