FROM node:20-alpine AS build
WORKDIR /app
COPY apps/jb-web/package.json ./
RUN npm install --registry=https://registry.npmmirror.com
COPY apps/jb-web/ .
RUN npm run build

FROM nginx:1.27-alpine
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
